Added page speed test with GL

diff --git a/.github/workflows/on_Branch.yml b/.github/workflows/on_Branch.yml
--- a/.github/workflows/on_Branch.yml
+++ b/.github/workflows/on_Branch.yml
@@ -143,31 +143,58 @@ jobs:
       - name: Run Unit Tests
         run: echo "Running unit tests..." 
 
-  # deploy_Backend_performance:
-  #   runs-on: ubuntu-latest
-  #   needs: build
-  #   steps:
-  #     - uses: actions/checkout@v2
-  #     - name: Run Unit Tests
-  #       run: echo "Running unit tests..." 
+  lighthouse_check:
+    runs-on: ubuntu-latest
+    needs: deploy_front_end
+    steps:
+      - name: Checkout repository code
+        uses: actions/checkout@v2
 
-  # k6_load_test:
-  #   name: k6 Load Test
-  #   runs-on: ubuntu-latest
-  #   needs: build
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v1
-  #     - name: Run local k6 test
-  #       uses: grafana/k6-action@v0.2.0
-  #       with:
-  #         filename: ${{ github.workspace }}/src/test/K6/perftest.js
-  #         flags: --out json=results.json
-  #     - name: Upload performance test results
-  #       uses: actions/upload-artifact@v3
-  #       with:
-  #         name: k6-report
-  #         path: results.json
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: 16
+
+      - name: Install jq
+        run: sudo apt-get install jq
+
+      - name: Install Lighthouse
+        run: npm install -g lighthouse
+
+      - name: Run Lighthouse and check performance
+        run: |
+          LIGHTHOUSE_SCORE=$(lighthouse --output=json --quiet --chrome-flags="--headless --no-sandbox" "https://www.blazedemo.com" | jq '.categories.performance.score * 100')
+          echo "Performance score: $LIGHTHOUSE_SCORE"
+          if [ $LIGHTHOUSE_SCORE -lt 60 ]; then
+            echo "error: Performance score is below 60. Blocking PR."
+            exit 1
+          fi     
+
+  deploy_Backend_performance:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/checkout@v2
+      - name: Run Unit Tests
+        run: echo "Running unit tests..." 
+
+  k6_load_test:
+    name: k6 Load Test
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v1
+      - name: Run local k6 test
+        uses: grafana/k6-action@v0.2.0
+        with:
+          filename: ${{ github.workspace }}/src/test/K6/perftest.js
+          flags: --out json=results.json
+      - name: Upload performance test results
+        uses: actions/upload-artifact@v3
+        with:
+          name: k6-report
+          path: results.json
 
   run_RestA_Tests:
         runs-on: ubuntu-latest  
@@ -223,7 +250,7 @@ jobs:
 
   run-selenium-tests:
     runs-on: windows-latest
-    needs: [deploy_backend,deploy_front_end]
+    needs: [deploy_backend,deploy_front_end,lighthouse_check]
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
